### ISSUE TITLE
Wrong permissions for ruby-build folder

### ISSUE THREAD

**Issue by ognevsky** [RiotGamesCookbooks/rbenv-cookbook#12]
Hi, 

I don't know if there is any error, but I have an issue with this https://github.com/RiotGames/rbenv-cookbook/blob/master/recipes/ruby_build.rb#L24

So, for the first time `ruby-build` folder is created with `root:root` permissions. During the next cooking I got an exception (because the `ruby-build` folder cannot be deleted). So, I need to change those permissions by hand (or remove this folder manually). 

I think it's wrong behavior, but I don't know how to fix this (except hardcoding my user and group).

Thanks, 
Andrey Ognevsky

**Comment by deepak** [comment]
by default ruby-build is installed to /usr/local

i install it on top of rbenv ie.node.set[:ruby_build][:prefix] = node[:rbenv][:root]

**Comment by ognevsky** [comment]
It's `knife-solo` problem: https://github.com/matschaffer/knife-solo/issues/86, i had to close it here, sorry for that.
