### ISSUE TITLE
/opt/rbenv/versions and /opt/rbenv/shims are owned by root

### ISSUE THREAD

**Issue by jhowarth** [RiotGamesCookbooks/rbenv-cookbook#35]
When rbenv is installed sometimes /opt/rbenv/versions and /opt/rbenv/shims are owned by root.  This causes a permissions error later when a new version is installed.

**Comment by sonnysideup** [comment]
This is no longer the case, please close this issue.

**Comment by reset** [comment]
@drywheat thanks for checking on that for us

**Comment by stefanosx** [comment]
I have the same problem, opt/rbenv belongs to rbenv user but all the files and folders in rbenv belongs to root, what is the fix?
