### ISSUE TITLE
`rbenv_ruby` causes `no such command `install'`

### ISSUE THREAD

**Issue by fiedl** [RiotGamesCookbooks/rbenv-cookbook#39]
When I try `rbenv_ruby` in order to install a ruby version, I get:

```
rbenv_ruby[2.0.0-p0] (main::default line 199) had an error: Chef::Exceptions::ShellCommandFailed:
---- Begin output of /opt/rbenv/bin/rbenv install 2.0.0-p0 ----
STDOUT:
STDERR: rbenv: no such command `install'
---- End output of /opt/rbenv/bin/rbenv install 2.0.0-p0 ----
```

And indeed, if I try `/opt/rbenv/bin/rbenv commands`, it lists:

```
commands
completions
exec
global
help
hooks
init
local
prefix
rehash
root
shell
shims
version
--version
version-file
version-file-read
version-file-write
version-name
version-origin
versions
whence
which
```

There is no `install` command included.

As I understand it, `rbenv install` is provided by `ruby_build`. 
I have `include_recipe "rbenv::ruby_build"` in my recipe, but apparently `rbenv install` does not work.

Can anyone confirm this? 
(Since I'm using the rbvenv cookbook for the first time, this could be my mistake in some regard.)

Thanks!

**Comment by ArnaudWopata** [comment]
I have the same problem.

**Comment by fiedl** [comment]
The new version solves this problem. Thanks.

For others having this issue:

Make sure to specify version '1.5.0'. You also have to specify the git repo as source until the cookbook is updated at the [opscode community source](http://community.opscode.com/cookbooks/rbenv).

``` ruby
# Cheffile  (librarian-chef)
# ...
cookbook 'rbenv', '>=1.5.0', git: 'https://github.com/RiotGames/rbenv-cookbook'
```
