### ISSUE TITLE
In order for a not-rbenv user to install gems, the permissions need to be looser

### ISSUE THREAD

**Issue by capoferro** [RiotGamesCookbooks/rbenv-cookbook#44]
When running bundle install as a not-rbenv user (even if the user is in the rbenv group), it prompts for a password to install the gems. We hacked around this issue by chmodding the directory structure to 775 after rbenv cookbook's recipes ran.

**Comment by donaldguy** [comment]
Fix pending in #52

**Comment by donaldguy** [comment]
Hey @bluepojo #52 merged yesterday. This should be resolved?

**Comment by capoferro** [comment]
Yep, ty!
