### ISSUE TITLE
rbenv_ruby ignores ruby_version and takes name as version instead

### ISSUE THREAD

**Issue by nextofsearch** [RiotGamesCookbooks/rbenv-cookbook#49]
``` ruby
rbenv_ruby "Ruby 1.9.3-p448" do
  ruby_version "1.9.3-p448"
  force true
end
```

If I run the above, I got the errors as below:

---- Begin output of /opt/rbenv/bin/rbenv install Ruby 1.9.3-p448 ----
 STDOUT:
 STDERR: ruby-build: definition not found: Ruby

 You can list all available versions with `rbenv install --list'.

 If the version you're looking for is not present, first try upgrading
 ruby-build. If it's still missing, open a request on the ruby-build
 issue tracker: https://github.com/sstephenson/ruby-build/issues
 ---- End output of /opt/rbenv/bin/rbenv install Ruby 1.9.3-p448 ----
 Ran /opt/rbenv/bin/rbenv install Ruby 1.9.3-p448 returned 2

 Cookbook Trace:

---

 /var/chef/cache/cookbooks/rbenv/providers/ruby.rb:35:in `block in class_from_file'

 Resource Declaration:

---

 # In /var/chef/cache/cookbooks/barebone/recipes/default.rb

  57: rbenv_ruby "Ruby #{node[:barebone][:ruby_version]}" do
  58:   ruby_version "#{node[:barebone][:ruby_version]}"
  59:   global true
  60: end
  61:

 Compiled Resource:

---

 # Declared in /var/chef/cache/cookbooks/barebone/recipes/default.rb:57:in `from_file'

 rbenv_ruby("Ruby 1.9.3-p448") do
   action :install
   retries 0
   retry_delay 2
   cookbook_name "barebone"
   recipe_name "default"
   ruby_version "1.9.3-p448"
   global true
 end

I had to change it as below to make it work:

``` ruby
rbenv_ruby "1.9.3-p448" do
  ruby_version "1.9.3-p448"
  force true
end
```

**Comment by allaire** [comment]
Same error here, any update on this?

**Comment by freerobby** [comment]
We're hitting this as well.

**Comment by freerobby** [comment]
I've fixed this here if anybody needs a quick fix: https://github.com/RiotGames/rbenv-cookbook/pull/107
