### ISSUE TITLE
[Question] Is gem_package supposed to still work?

### ISSUE THREAD

**Issue by allaire** [RiotGamesCookbooks/rbenv-cookbook#72]
Hi, I installed ruby 2.0 globally using the rbenv-cookbook. My question is, in my other recipes, should I change all my gem_package to rbenv_gem or both should work?

**Comment by rossjourdain** [comment]
+1 I'm having trouble with the passenger_apache2 cookbook that is using gem_package and doesn't manage to find the Ruby I just installed...

**Comment by reset** [comment]
@allaire `rbenv_gem` does the job of installing the gem for that specific Ruby managed by rbenv. You would need to use that resource if you wanted the gem available to you there.

The `gem_package` resource does the job of installing the gem for your system Ruby. In many cases this will be the  Ruby that is currently executing Chef.

The `chef_gem` resource does the job of installing a gem for the Ruby currently executing Chef and it does so at compile time so it is available to your recipes without pain.

Please close if this satisfies your question :)

**Comment by allaire** [comment]
Good thanks.
