### ISSUE TITLE
running default recipe causes ruby_build to be installed

### ISSUE THREAD

**Issue by lukewpatterson** [RiotGamesCookbooks/rbenv-cookbook#8]
rbenv::default [runs rbenv::system_install](https://github.com/RiotGames/rbenv-cookbook/blob/master/recipes/default.rb#L22), which [relies on rbenv_installation](https://github.com/RiotGames/rbenv-cookbook/blob/master/recipes/system_install.rb#L23), which [runs rbenv::ruby_build](https://github.com/RiotGames/rbenv-cookbook/blob/master/definitions/rbenv_installation.rb#L48)

All paths result in ruby_build being installed.  Is this intentional?

**Comment by deepak** [comment]
has been solved. now this cookbook has default which install rbenv and ruby_build which install ruby_build

**Comment by deepak** [comment]
@reset i think this bug is solved now. can close it ?

**Comment by lukewpatterson** [comment]
Sounds good to me.  Thanks!

**Comment by reset** [comment]
@deepak thanks for following up on this
