### ISSUE TITLE
Failure when trying to install mruby (which depends on rbenv)

### ISSUE THREAD

**Issue by timuckun** [RiotGamesCookbooks/rbenv-cookbook#88]
Not sure where the fault lies exactly but it looks like rbenv recipe is throwing the error.  Here is the issue I filed with the mruby project

https://github.com/higanworks-cookbooks/mruby/issues/1

**Comment by reset** [comment]
@timuckun You're running Chef Client under a very old version of Ruby, 1.8, which is not supported by this cookbook.
