### ISSUE TITLE
Missing tags: 1.7.0 and 1.7.1

### ISSUE THREAD

**Issue by docwhat** [RiotGamesCookbooks/rbenv-cookbook#94]
According to http://community.opscode.com/cookbooks/rbenv you've released versions 1.7.0 and 1.7.1.

However, I don't see tags 'v1.7.0' and 'v1.7.1' -- Did you forget to push the tags?

**Comment by apswood** [comment]
Please can this be tagged as ruby will not build without patching on the latest fedora/centos/RHEL due to openssl with 'no-ec2m' (https://bugs.ruby-lang.org/projects/ruby-trunk/repository/revisions/41808/). The support for patch attribute in the rbenv_ruby LWRP was added from 1.7.0 onwards.

**Comment by docwhat** [comment]
@reset ping?

**Comment by ivey** [comment]
I'll check on this over the weekend.

**Comment by docwhat** [comment]
Thanks, @ivey

**Comment by reset** [comment]
@docwhat I pushed the tags up, sorry about that

**Comment by docwhat** [comment]
Thanks! No worries. We all forget things.  That's why we have issue trackers to remind you. :-) :grinning:
